const LOGIN_REQUEST = 'AUTH/LOGIN_REQUEST';
const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS';
const LOGIN_ERROR = 'AUTH/LOGIN_ERROR';

const LOGOUT_REQUEST = 'AUTH/LOGOUT_REQUEST';
const LOGOUT_SUCCESS = 'AUTH/LOGOUT_SUCCESS';
const LOGOUT_ERROR = 'AUTH/LOGOUT_ERROR';

export {
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_ERROR,
    LOGOUT_REQUEST,
    LOGOUT_SUCCESS,
    LOGOUT_ERROR,
};
