export const FETCH_USERS_REQUEST = 'USERS/FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'USERS/FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'USERS/FETCH_USERS_ERROR';

export const ADD_FETCH_USERS_SUCCESS = 'USERS/ADD_FETCH_USERS_SUCCESS';
